### ISSUE TITLE
Is too dark

### ISSUE THREAD

**Issue by salomonsdaniel** [Phibog/stonky-theme#1]
Please fix

**Comment by Phibog** [comment]
Hi @salomonsdaniel,

Thank you for your feedback! I understand that the theme may seem too dark for some users. The chosen blue color and the overall dark tone are part of a personal preference to create a coding environment that is easy on the eyes, especially during long coding sessions. Darker themes can help reduce eye strain and minimize glare, which is particularly beneficial when working in low-light conditions.

However, I appreciate that everyone has different preferences, and I'll take your feedback into consideration for future updates. In the meantime, if you'd like to customize the theme to better suit your needs, feel free to tweak the colors in your settings.

Thanks again for sharing your thoughts, and happy coding!
